[package]
name = "rusty_vault"
version = "0.1.0"
edition = "2021"

[dependencies]
argonautica = "0.2.0"
chacha20poly1305 = "0.10.1"
rand = "0.9.0-alpha.1"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
rpassword = "7.3.1"